import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

import StoreProvider from "./StoreProvider";


const montserrat = Montserrat({
  variable: "--font-montserrat", // ✅ Correct and clear
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable}  antialiased`}
      >

        <StoreProvider>{children}</StoreProvider>

      </body>
    </html>
  );
}
